# docker-compose.yml
services:
  postgres:
    image: postgres:15-alpine
    container_name: maestro_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: maestro_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./internal/database/init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d maestro_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - maestro-network

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: maestro_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - maestro-network

  maestro-backend:
    container_name: maestro_backend
    build: .
    ports:
      - "8080:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - MAESTRO_RABBITMQ_HOST=rabbitmq
      - MAESTRO_RABBITMQ_PORT=5672
      - MAESTRO_RABBITMQ_USER=guest
      - MAESTRO_RABBITMQ_PASSWORD=guest
      - MAESTRO_SERVER_PORT=8000
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    networks:
      - maestro-network

networks:
  maestro-network:
    name: maestro-network
    driver: bridge

volumes:
  postgres_data:
