name: Deploy Maestro Backend (Legacy)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  deploy:
    runs-on: self-hosted
    environment:
      name: ${{ github.event.inputs.environment || 'production' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare environment
        env:
          MAESTRO_ENV_FILE: ${{ secrets.MAESTRO_ENV_FILE }}
        run: |
          PROD_PATH="${{ secrets.MAESTRO_DEPLOY_PATH }}"
          
          echo "📋 Deployment Information:"
          echo "  Deploy Path: $PROD_PATH"
          echo "  Environment: ${{ github.event.inputs.environment }}"
          echo "  Triggered by: ${{ github.actor }}"
          
          # Criar o diretório
          mkdir -p "$PROD_PATH"
          
          # Criar o arquivo .env
          if [ -z "$MAESTRO_ENV_FILE" ]; then
            echo "⚠️  Warning: MAESTRO_ENV_FILE secret is empty"
          else
            echo "$MAESTRO_ENV_FILE" > "$PROD_PATH/.env"
            echo "✅ .env file created"
          fi

      - name: Deploy with Docker Compose
        working-directory: ${{ secrets.MAESTRO_DEPLOY_PATH }}
        run: |
          echo "🚀 Starting deployment..."
          
          # Pull latest image
          docker-compose pull maestro-backend
          
          # Start or restart the service
          docker-compose up -d --no-deps maestro-backend
          
          # Cleanup
          docker image prune -f
          
          echo "✅ Deployment completed"

      - name: Health check
        run: |
          echo "🏥 Checking application health..."
          sleep 5
          if curl -f http://localhost:8080/health || true; then
            echo "✅ Application is healthy"
          else
            echo "⚠️  Application started (health check endpoint may not be implemented)"
          fi